print ('BIENVENID@')

INVERSION_SOCIO_A = int(input('El socio A invierte: $'))
INVERSION_SOCIO_B = int(input('El socio B invierte: $'))
INVERSION_SOCIO_C = int(input('El socio C invierte: $'))
print ()
INVERSION_TOTAL = (INVERSION_SOCIO_A + INVERSION_SOCIO_B + INVERSION_SOCIO_C)
print ('La inversion total es de: ')
print (str(INVERSION_TOTAL))
print ()
PORCENTAJE_INVERSION_A = ((INVERSION_SOCIO_A / INVERSION_TOTAL) *100)
print ('El porcentaje de inversion del socio A es de: ')
print (PORCENTAJE_INVERSION_A)
print ()
PORCENTAJE_INVERSION_B = ((INVERSION_SOCIO_B / INVERSION_TOTAL) *100)
print ('El porcentaje de inversion del socio B es de: ')
print (PORCENTAJE_INVERSION_B)
print ()
PORCENTAJE_INVERSION_C = ((INVERSION_SOCIO_C / INVERSION_TOTAL) *100)
print ('El porcentaje de inversion del socio C es de: ')
print (PORCENTAJE_INVERSION_C)
print ()
print ('GRACIAS!!!')

print ()
print ()
print ()
print ('***Desing by @xcabezaderadiox***')
