print ('BIENVENID@ ALUMN@')

print ('Estas son las siguientes notas en Analisis: ')
print ('Nota examen')
NOTA_EXAMEN = int(input())
print ('TP NUMERO 1')
TP1 = int(input())
print ('TP NUMERO 2')
TP2 = int(input())
print ('TP NUMERO 3')
TP3 = int(input())
print ('Promedio de TPS')
PROMEDIO_DE_TPS = (TP1 + TP2 + TP3) / 3
print (str(PROMEDIO_DE_TPS))
NOTA_FINAL_ANALISIS = (PROMEDIO_DE_TPS * 0.10) + (NOTA_EXAMEN * 0.90)
print ('El promedio final de Analisis es de: ')
print (str(NOTA_FINAL_ANALISIS))
print ()
print ('Estas son las siguientes notas en Algebra: ')
print ('Nota examen')
NOTA_EXAMEN = int(input())
print ('TP NUMERO 1')
TP1 = int(input())
print ('TP NUMERO 2')
TP2 = int(input())
print ('Promedio de TPS')
PROMEDIO_DE_TPS = (TP1 + TP2) / 3
print (str(PROMEDIO_DE_TPS))
NOTA_FINAL_ALGEBRA = (PROMEDIO_DE_TPS * 0.20) + (NOTA_EXAMEN * 0.80)
print ('El promedio final de Algebra es de: ')
print (str(NOTA_FINAL_ALGEBRA))
print ()
print ('Estas son las siguientes notas en Programacion: ')
print ('Nota examen')
NOTA_EXAMEN = int(input())
print ('TP NUMERO 1')
TP1 = int(input())
print ('TP NUMERO 2')
TP2 = int(input())
print ('TP NUMERO 3')
TP3 = int(input())
print ('Promedio de TPS')
PROMEDIO_DE_TPS = (TP1 + TP2 + TP3) / 3
print (str(PROMEDIO_DE_TPS))
NOTA_FINAL_PROGRAMACION = (PROMEDIO_DE_TPS * 0.10) + (NOTA_EXAMEN * 0.90)
print ('El promedio final de Programacion es de: ')
print (str(NOTA_FINAL_PROGRAMACION))
print ()
print ('El promedio general sera de: ')
PROMEDIO_GENERAL = (NOTA_FINAL_ALGEBRA + NOTA_FINAL_ANALISIS + NOTA_FINAL_PROGRAMACION) / 3
print (str(PROMEDIO_GENERAL))
print ()
if PROMEDIO_GENERAL > 6:
    print ('Felicitaciones!!!!!!')
else:
    print ('A estudiar mas por favor Alumno')
print ()
print ('GRACIAS')

print ()
print ()
print ()
print ('***Desing by @xcabezaderadiox***')
