#!/usr/bin/python3

print ('BIENVENID@')

def Pulsaciones (a):

    PULSASIONES_CADA_DIEZ_SEGUNDOS_SEGUN_EDAD = (220 - a) / 10
    print ('Sus pulsaciones cada diez segundos seran de: ')
    print (str(PULSASIONES_CADA_DIEZ_SEGUNDOS_SEGUN_EDAD))

EDAD = int(input('Por favor ingrese su edad: '))
Pulsaciones(EDAD)


print ('GRACIAS!!!')

print ()
print ()
print ()
print ('***Desing by @xcabezaderadiox***')

