#!/usr/bin/python3

def Porcentajes(a,b):
    TOTAL_DE_ALUMNOS = (a + b)
    PORCENTAJE_DE_MUJERES = (( a / TOTAL_DE_ALUMNOS) * 100) 
    print ('PORCENTAJE DE MUJERES CURSANDO: ')
    print (PORCENTAJE_DE_MUJERES)
    PORCENTAJE_DE_HOMBRES = (( b / TOTAL_DE_ALUMNOS) * 100)
    print ('PORCENTAJE DE HOMBRES CURSANDO: ')
    print (PORCENTAJE_DE_HOMBRES)


TOTAL_DE_MUJERES = int(input('Cantidad de mujeres en curso son: '))
TOTAL_DE_HOMBRES = int(input('Cantidad de hombres en curso son: '))
Porcentajes(TOTAL_DE_MUJERES,TOTAL_DE_HOMBRES)


print ()
print ()
print ()
print ('***Desing by @xcabezaderadiox***')

