#!/usr/bin/python3

print ('BIENVENID@')

def Precio(a,b):

    if a <= 2:
        PRECIO_FINAL = (b * a) 
    
    elif a > 2 and a <= 5:
        PRECIO_FINAL = (b * a -(b * a * 0.10))
    
    elif a > 5 and a <= 10:
        PRECIO_FINAL = (b * a -(b * a * 0.15))
        
    else:
        PRECIO_FINAL = (b * a -(b * a * 0.20))    

    print ('Su valor final de compra es de: ')   
    print (PRECIO_FINAL)
    print ('GRACIAS!!!')

COMPRA = int(input('Hola por favor ingrese su cantidad de KG de Manzanas compradas:   '))
PRECIO_POR_KILO = 5
Precio(COMPRA,PRECIO_POR_KILO)

print ()
print ()
print ()
print ('***Desing by @xcabezaderadiox***')
