#!/usr/bin/python3

def Promedio():
    global Numero_uno
    global Numero_dos
    global Numero_tre
    Promedio = ((Numero_uno + Numero_dos + Numero_tres) / 3)   
    print (str(Promedio))

Numero_uno = int (input( 'Inserte primer nuemero: '))
Numero_dos = int (input( 'Inserte segundo numero: '))
Numero_tres = int (input( 'Inserte tercer numero: '))
Promedio()


