#!/usr/bin/python3

print ('BIENVENID@ ALUMNO')


def Promedio(a,b,c,d,e,f,g):

    PROMEDIO = ((a + b + c + d + e + f + g ) / 7 )

    print ('Su promedio final sera de: ')
    print (str(PROMEDIO))


CALIFICACION_UNO = int(input('Hola por favor ingrese su 1er calificacion:   '))
CALIFICACION_DOS = int(input('Hola por favor ingrese su 2da calificacion:   '))
CALIFICACION_TRES = int(input('Hola por favor ingrese su 3er calificacion:   '))
CALIFICACION_CUATRO = int(input('Hola por favor ingrese su 4ta calificacion:   '))
CALIFICACION_CINCO = int(input('Hola por favor ingrese su 5ta calificacion:   '))
CALIFICACION_SEIS = int(input('Hola por favor ingrese su 6ta calificacion:   '))
CALIFICACION_SIETE = int(input('Hola por favor ingrese su 7ma calificacion:   '))
Promedio(CALIFICACION_UNO,CALIFICACION_DOS,CALIFICACION_TRES,CALIFICACION_CUATRO,CALIFICACION_CINCO, CALIFICACION_SEIS,CALIFICACION_SIETE)
print ('GRACIAS!!!')

print ()
print ()
print ()
print ('***Desing by @xcabezaderadiox***')
